### ISSUE TITLE
Logs spammed with FIXME: query end, but query_start == 0 and now also FIXME: transaction end, but xact_start == 0

### ISSUE THREAD

**Issue by svb007** [pgbouncer/pgbouncer#277]
I've seen that this was suggested before, and I attach the patch that fixed this issue for me (by downgrading the log priority to debug)

[fixme_logspam.patch.txt](https://github.com/pgbouncer/pgbouncer/files/1657926/fixme_logspam.patch.txt)

**Comment by topharley** [comment]
In my case I could see errors in PGBouncer's log:

  FIXME: query end, but query_start == 0
  FIXME: transaction end, but xact_start == 0

And from NPGSQL exceptions:
  Npgsql.NpgsqlException (0x80004005): Exception while reading from stream ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream. at Npgsql.ReadBuffer.<Ensure>d__27.MoveNext()...

And finally it was fixed by setting "No Reset On Close=True" in connection string witch is described here https://www.npgsql.org/doc/performance.html

Errors occured in only one case:
1) Using client pooling build in npgsql
2) Using PGBouncer for server pooling
3) PGBouncer used in "transaction" mode
4) Using UPDATE queries in called stored procedure (SELECT are working fine)
5) Multithreading client >=10 threads in app
6) Sending string parameter to SP with length >= 4000 chars (small strings are working fine)

Same behavior on 3.2.7 and 4.0.3

Disabled code:
if (!Settings.NoResetOnClose && DatabaseInfo.SupportsDiscard)
{
	if (PreparedStatementManager.NumPrepared > 0)
	{
		...
	}
	else
	{
		// There are no prepared statements.
		// We simply send DISCARD ALL which is more efficient than sending the above messages separately
		PrependInternalMessage(PregeneratedMessage.DiscardAll); // <-- THIS WILL NO BE CALLED!!!!!!!!!!!!!!!!!!!!!!!!!
	}
} 

I guess this param must be always switched to "No Reset On Close=True" when using PGBouncer in transaction mode because PGBouncer switches connection for each transaction so logic of DISCARD ALL looses sense. Correct me pleas if i am wrong.

**Comment by kleptog** [comment]
This is possibly fixed by #253.

**Comment by wanziforever** [comment]
> 
> 
> This is possibly fixed by #253.

the problem is still exist, not ony under async mode, if a request  contains multiple transaction requests, and the server will receive mutiple response sequencely, and the problem will be reproduced.

**Comment by topharley** [comment]
Another case of using **pgbouncer** in transaction mode with **Npgsql** that would spam your logs:

SQL: 
```
CREATE OR REPLACE FUNCTION test1()  RETURNS int LANGUAGE sql AS $$ select 100500; $$;
```
c#:
```
using (var con = new NpgsqlConnection("User ID=user;Password=pass;Host=myip;Port=6432;Database=postgres"))
{
	con.Open();
	using (var trans = con.BeginTransaction())
	{
		var readCommand = new NpgsqlCommand("test1", con, trans);
		readCommand.CommandType = CommandType.StoredProcedure;
		var res = readCommand.ExecuteScalar(); //spammed here
		trans.Commit();
	}
}
```

And this will write 2 lines in pgbouncer log on each call:
```FIXME: query end, but query_start == 0
FIXME: query end, but query_start == 0```

The most important part here is that we are using explicit transaction.
I guess there are 2 problems:
1) slog_warning(client, "FIXME: query end, but query_start == 0"); where slog_debug should be used instead.
2) there is somethng in transactions handling in Npgsql not compatible to pgbouncer transactions handling in transaction mode

**Comment by roji** [comment]
Not sure what the status of this is... In case it helps, here's a wireshark dump of an exchange between Npgsql and pgbouncer which reproduces this:

[FIXME_Warning.zip](https://github.com/pgbouncer/pgbouncer/files/4333382/FIXME_Warning.zip)

The C# code which triggers this change is the following (contributed by @Bschitter in https://github.com/npgsql/npgsql/issues/2522#issuecomment-598127613):

```c#
class Program
{
    static void Main(string[] args)
    {
        using (var con = new NpgsqlConnection("Host=localhost;Port=6432;Database=test;Username=test;Password=test;Server Compatibility Mode=NoTypeLoading;No Reset On Close=true"))
        {
            con.Open();
            using (var trans = con.BeginTransaction())
            {
                trans.Commit();
            }

            con.Close();
        }
    }
}
```

PS Note probable duplicate issue #376 which may be closable.

**Comment by nathan-c** [comment]
It would be great to get this change (https://github.com/pushpay/pgbouncer/pull/1) merged (if indeed making the message debug is the right way to go). Having this volume of logs can get costly quickly when using GCP Logging.

**Comment by kos12345** [comment]
any solution?
