### ISSUE TITLE
Problem with 08P01: server conn crashed?

### ISSUE THREAD

**Issue by ivzhenko** [pgbouncer/pgbouncer#714]
When using PgBouncer, an error occurs periodically under load (example from a client application) - 08P01: server conn crashed?
General scheme: Client app (ORM) -> PgBouncer -> Postgresql (PgBouncer and Postgresql are on the same server)

### Versions
**App** 
.Net ORM + Npgsql.EntityFrameworkCore.PostgreSQL/5.0.2

**PgBouncer** 
1.16.0
libevent 2.0.21-stable
adns: libc-2.17
tls: OpenSSL 1.0.2k-fips  26 Jan 2017

**PostgreSQL** 
12.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**PgBouncer** config:
```
[databases]
* = host=localhost port=5432

[pgbouncer]
listen_port = 6432
listen_addr = *
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
;auth_query = SELECT username, password from pgbouncer.get_auth($1)
;logfile = /var/log/pgbouncer/pgbouncer.log
;pidfile = /var/run/postgresql/pgbouncer.pid
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid
admin_users = postgres
stats_users = stats, postgres
default_pool_size = 1000
max_client_conn = 300
max_db_connections = 0
min_pool_size = 0
pool_mode = transaction
reserve_pool_size = 10
reserve_pool_timeout = 5
query_timeout = 0
ignore_startup_parameters =  search_path
unix_socket_dir = /var/run/pgbouncer
```

### Logs:
**App**
```
Npgsql.PostgresException (0x80004005): 08P01: server conn crashed?
at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
 Exception data:
 Severity: FATAL
 SqlState: 08P01
 MessageText: server conn crashed?
```

**PgBouncer**
```
2022-05-06 12:24:24.130 EET [58369] LOG C-0x23859a8: SomeDB/SomeUser@10.0.9.55:50518 login attempt: db=SomeDB user=SomeUser tls=no
2022-05-06 12:24:24.130 EET [58369] LOG C-0x7fd3f1ae4578: SomeDB/SomeUser@10.0.9.55:50520 login attempt: db=SomeDB user=SomeUser tls=no
2022-05-06 12:24:44.638 EET [58369] LOG C-0x23a7928: SomeDB/SomeUser@10.0.9.55:50746 login attempt: db=SomeDB user=SomeUser tls=no
2022-05-06 12:24:46.736 EET [58369] LOG S-0x2362bf8: SomeDB/SomeUser@[::1]:5432 closing because: server conn crashed? (age=784s)
2022-05-06 12:24:46.736 EET [58369] LOG C-0x23a7928: SomeDB/SomeUser@10.0.9.55:50746 closing because: server conn crashed? (age=2s)
2022-05-06 12:24:46.736 EET [58369] WARNING C-0x23a7928: SomeDB/SomeUser@10.0.9.55:50746 pooler error: server conn crashed?
2022-05-06 12:24:46.822 EET [58369] LOG S-0x2362bf8: SomeDB/SomeUser@[::1]:5432 new connection to server (from [::1]:45182)
```

**Postgresql**
```
2022-05-06 12:24:46.727 EET,"SomeUser","SomeDB",8528,"::1:45074",620a2add.2150,3,"idle",2022-05-06 12:11:41 EET,96/0,0,FATAL,08P01,"invalid frontend message type 0",,,,,,,,,""				
2022-05-06 12:24:46.727 EET,"SomeUser","SomeDB",8528,"::1:45074",620a2add.2150,4,"idle",2022-05-06 12:11:41 EET,,0,LOG,00000,"disconnection: session time: 0:13:04.903 user=SomeUser database=SomeDB host=::1 port=45074",,,,,,,,,""	
```

**Comment by blueyed** [comment]
Just for reference: https://github.com/pgbouncer/pgbouncer/issues/347 (and my comment there: https://github.com/pgbouncer/pgbouncer/issues/347#issuecomment-1164196085).

**Comment by minh-nguyen-carsales** [comment]
For anyone running in to the same issue with `Npgsql`, we fixed it by turning off the pooling options that enables by default by Npgsql, also suggested in heir [documentation](https://www.npgsql.org/doc/compatibility.html#pgbouncer). My guess is that Npgsql keeps some connections that was already closed by pgbouncer.

**Comment by ghabre** [comment]
hi, i faced the issue and tried the solution Pooling=false. But then we switched from Azure Single Postgre server to Flexible Postgre with pgbouncer. it seems in flexible server this flag is affecting pgbouncer performance whenever there's a high load as if pooling it not working properly and we get various connection timeout and drops. so removed it for now, and if the original issue appears again will see how else to fix

**Comment by JelteF** [comment]
I've reopened this issue because I just pushed a commit to #845 that should hopefully fix this issue. If any of you could try out #845 to confirm that it indeed fixes the problem.

**Comment by sasog23** [comment]
works find with PostgreSQL 15.5 (Debian 15.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

PostgreSQL 13.13 (Ubuntu 13.13-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
still getting an error 08P01: server conn crashed?, even after adding Pooling=false,
also, when i add Pooling=false, appilcation_name is empty in the pg_stat_activity
my connstr: Server=1.1.1.1;Port=6432;Database=aio;User Id=xxx;Password=www;Application Name=my_app_name;No Reset On Close=true;Timeout=300;CommandTimeout=300;Pooling=false;

**Comment by rajrajsahil** [comment]
I am still getting these errors intermittently
08P01: invalid frontend message type 49
08P01: invalid frontend message type 34
08P01: server conn crashed

My connection string is Server=lh-psql-app-np-eus-d2.postgres.database.azure.com;Database=psqldb-saia-pilot-01;Port=6432;User Id=psqladmin;Password=AxClN6msR1MhkMPw;Maximum Pool Size=200;Timeout=30; No Reset On Close=true;

I am using PostgreSQL 14.9 with pgbouncer.

**Comment by ghabre** [comment]
We're currently using this connection string, not sure if it helps. We haven't faced this in a while. Note that setting Pooling=false is disabling the connection pooling that is handled from the .NET client library's end, and not from the server's end. By removing Pooling=false and allowing this pooling, it seems to be helping avoid the issue:
Server=***-flex.postgres.database.azure.com;Database=***;Port=6432;User Id=***;Password=***;CommandTimeout=300;Timeout=300;Ssl Mode=Require;No Reset On Close=true;Trust Server Certificate=true;Maximum Pool Size=200
